spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrix_core
    username: nutrix_core_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
