spring:
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrix_auth
    username: nutrix_auth_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: INFO

oauth:
  google:
    client-id: 1070270542749-5230c4odd2duh8rdlkh3ds6oudt3obk2.apps.googleusercontent.com
    client-secret: faDlEHXG6DfCSu7BbBSmq7B1
