spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nutrix_auth
    username: nutrix_auth_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    ROOT: INFO
